Reselling/UIView/Controllers/MainController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Reselling.Domain.Infrastructure;
using Reselling.Domain.Models.Authentication;
using Reselling.Domain.Models.Data;
using Reselling.UIView.Models.Data;
using System;
using System.Linq;

namespace Resaling.Controllers
{
    public class MainController : Controller
    {

        IRepository _repo;
        readonly int _eventsPageSize = 4;
        readonly int _ticketsForEventsPageSize = 4;


        public MainController(IRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Events(int? page)
        {
            int _page = (int)(page ?? 1);

            EventsListViewModel _eventsList = new EventsListViewModel
            {
                EventsItems = _repo.GetEvents().Skip((_page - 1) * _eventsPageSize).Take(_eventsPageSize),
                PagingInfo = new PagingInfo
                {
                    CurentPage = _page,
                    ItemsRerPage = _eventsPageSize,
                    TotalItems = _repo.GetEvents().Count()
                }
            };


            return View(_eventsList);
        }

        public IActionResult TicketsEvent(int? id, int? page)
        {
            EventTicketsListView _eventsList;

            if (id != null)
            {
                int _id = (int)id;

                Event _event = _repo.GetEventById(_id);

                if (_event != null)
                {
                    int _page = (int)(page ?? 1);
                    _eventsList = new EventTicketsListView
                    {
                        Event = _event,


                        PagingInfo = new PagingInfo
                        {
                            CurentPage = _page,
                            ItemsRerPage = _ticketsForEventsPageSize,
                            TotalItems = _event.Tickets.Count()
                        }
                    };
                    return View(_eventsList);
                }
            }
            return RedirectToAction("Events");
        }


        [HttpGet]
        [Authorize]
        public IActionResult SellTickets(int? id)
        {


            if (id != null)
            {
                int _id = (int)id;

                Event _event = _repo.GetEventById(_id);

                if (_event != null)
                {

                    return View(_event);
                }
            }
            return RedirectToAction("Events");
        }

        [HttpPost]
        [Authorize]
        public IActionResult SellTickets(Ticket ticket)
        {
            if (ticket.EventId > 0)
            {
                User _curUser = _repo.GetUserByEmail(HttpContext.User.Identity.Name);

                if (_curUser != null)
                {
                    ticket.UserId = _curUser.Id;
                    ticket.TicketStatusId = _repo.GetTicketStatusByName(TicketStatusEnum.SellingTicket.ToString("g")).Id;
                    _repo.AddTicket(ticket);
                }
            }

            return RedirectToAction("TicketsEvent", new { id = ticket.EventId });
        }


        public IActionResult MakeOrder(int? id, string returnUrl)
        {
            if (id != null)
            {
                int _id = (int)id;

                User _curUser = _repo.GetUserByEmail(HttpContext.User.Identity.Name);
                Order _order = new Order { TicketId = id, UserId = _curUser.Id, OrderStatusId = _repo.GetOrderStatusByName(OrderStatusEnum.WaitingOrder.ToString("g")).Id };
                _repo.AddOrder(_order);
                _repo.SetTicketStatus(_id, TicketStatusEnum.WaitingTicket);

                return LocalRedirect(returnUrl);

            }

            return LocalRedirect("Error");
        }

        public IActionResult ConfirmOrder(int? ticketId, string returnUrl)
        {
            if (ticketId != null)
            {
                int _ticketId = (int)ticketId;

                Order _order = _repo.GetOrderByTicketId(_ticketId);

                if (_order != null)
                {
                    _repo.SetOrderStatus(_order.Id, OrderStatusEnum.ConfirmedOrder);

                    _repo.SetTicketStatus(_ticketId, TicketStatusEnum.SoldTicket);

                    _repo.AddTrackingNumberToOrder(_order.Id, new Random().Next(1, 10000));

                    return LocalRedirect(returnUrl);
                }
            }
            return LocalRedirect("Error");
        }

        public IActionResult RejectOrder(int? ticketId, string returnUrl)
        {
            if (ticketId != null)
            {
                int _ticketId = (int)ticketId;

                Order _order = _repo.GetOrderByTicketId(_ticketId);

                if (_order != null)
                {
                    _repo.SetOrderStatus(_order.Id, OrderStatusEnum.RejectedOrder);

                    _repo.SetTicketStatus(_ticketId, TicketStatusEnum.SellingTicket);

                    _repo.AddErrorMesageToOrder(_order.Id, "Sorry man!");

                    return LocalRedirect(returnUrl);
                }
            }
            return LocalRedirect("Error");
        }



        public IActionResult SetLanguage(string culture, string returnUrl)
        {

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );


            return LocalRedirect(returnUrl);

            // return View(System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName);culture
        }
        public IActionResult Error()
        {
            return View("Error");
        }

    }
}

Reselling/UIView/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer


<div class="collapse navbar-collapse" id="navbar-ex-collapse">
    @if (Context.User.IsInRole("Admin"))
    {
        <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false"> @Localizer["AdminManagement"] <span class="caret"></span>
                </a>
                <ul class='dropdown-menu'>
                    <li>
                        <a asp-action="Cities" asp-controller="Admin">@Localizer["ManageCities"]</a>
                    </li>
                    <li>
                        <a asp-action="Venues" asp-controller="Admin">@Localizer["ManageVenues"]</a>
                    </li>
                    <li>
                        <a asp-action="Events" asp-controller="Admin">@Localizer["ManageEvents"]</a>
                    </li>
                    <li>
                        <a asp-action="Users" asp-controller="Admin">@Localizer["ManageUsers"]</a>
                    </li>
                </ul>
            </li>
        </ul>
    }
</div>

Reselling/UIView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reselling</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header navbar-left">
                @Html.ActionLink("Reselling", "Events", "Main", new { page = 1 }, new { @class = "navbar-brand"  })
            </div>
            <div class="navbar-header navbar-left">
                @await Html.PartialAsync("_AdminPartial")
            </div>
            <div class="navbar-header navbar-right">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>




    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; 2016 - Reselling by slobbery</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>





    @RenderSection("scripts", required: false)
</body>
</html>

Reselling/UIView/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> _locOptions

@{
    CultureInfo selectedCulture = Context.Features.Get<IRequestCultureFeature>().RequestCulture.Culture;
    IList<CultureInfo> cultures = _locOptions.Value.SupportedUICultures;
}

<div title="@Localizer["SelectLanguage"]">
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">
                <img src="/images/flags/@String.Format("{0}.png",selectedCulture.Name)"/>
              <span class="caret"></span>
            </a>
            <ul class='dropdown-menu'>
                @foreach (var culture in cultures)
                {
                    <li>
                        <a asp-action="SetLanguage" asp-controller="Main" asp-route-culture="@culture.Name"
                           asp-route-returnUrl="@Context.Request.Path">
                            <img src="/images/flags/@String.Format("{0}.png",culture.Name)"/>
                            @culture.DisplayName
                        </a>
                    </li>
                }
            </ul>
        </li>
    </ul>
</div>